name: CI
run-name: CI

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to build'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  checks:
    name: "Run checks"
    runs-on: ubuntu-22.04
    outputs:
      ref: ${{ steps.check_input.outputs.ref }}
    steps:
      - name: Check input
        id: check_input
        run: |
          if [[ -z "${{ github.event.inputs.ref }}" ]]; then
            echo "No input provided, fetching latest Zed published version"
            latest_zed="$(curl -sL https://api.github.com/repos/zed-industries/zed/releases | jq -r '.[0].tag_name')"
            echo "ref=${latest_zed}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          fi

  build:
    name: "Build Zed"
    runs-on: windows-latest
    needs: [checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout Zed
        uses: actions/checkout@v4
        with:
            repository: zed-industries/zed
            ref: ${{ needs.checks.outputs.ref }}
            path: zed

      - name: Build Zed
        id: zed-build
        uses: ./.github/actions/zed-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: zed
          path: |
            ./zed/target/release/zed.zip
            ./zed/target/release/zed.exe.sha256
            ./zed/target/release/zed.zip.sha256
            ./zed/target/release/zed.pdb.zip
            ./zed/target/release/zed.pdb.zip.sha256
          if-no-files-found: error

      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
